services:
  velxio:
    container_name: velxio
    image: davidmonterocrespo/velxio:master
    restart: unless-stopped
    networks:
      - homelab-net
    # ports:
    #   - "3080:80"
    volumes:
      - ./data:/app/data
      - ./data/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - TZ=Asia/Dhaka
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.velxio.rule=Host(`velxio.lab.sayem.pro`)"
      - "traefik.http.routers.velxio.entrypoints=websecure"
      - "traefik.http.routers.velxio.tls=true"
      - "traefik.http.routers.velxio.tls.certresolver=cf-letsencrypt"
      - "traefik.http.services.velxio.loadbalancer.server.port=80"

networks:
  homelab-net:
    external: true