# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  cloudflared:
    container_name: cloudflared-pihole
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    # Embed cloudflared configuration directly in the command
    command:
      - proxy-dns
      - --upstream
      - https://dns.nextdns.io/c74829/pihole
      - --upstream
      - https://1.1.1.1/dns-query
      - --upstream
      - https://1.0.0.1/dns-query
      - --port
      - "5053"
      - --address
      - "0.0.0.0" # Crucial for Docker: listen on all interfaces inside the container
    # ports: # Optional: expose cloudflared port to host if you want to test it directly
    #   - "127.0.0.1:5053:5053/tcp"
    #   - "127.0.0.1:5053:5053/udp"
    networks:
      - homelab-net

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      # - "8090:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      # - "8443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      # Set the appropriate timezone for your location from
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
      TZ: "Asia/Dhaka"
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: "damndns"
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: "all"
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - "./etc-pihole:/etc/pihole"
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.rule=Host(`pihole.lab.sayem.pro`)"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=cf-letsencrypt"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      #- NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      #- SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
    depends_on:
      - cloudflared
    networks:
      - homelab-net
