services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    networks:
      - homelab-net
    volumes:
      - ./ollama_data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 4G

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    networks:
      - homelab-net
    volumes:
      - ./open-webui:/app/backend/data
    environment:
      - TZ=Asia/Dhaka
      - 'ENABLE_OLLAMA=true'
      - 'ENABLE_MCP=true'
      - 'VECTOR_DB=pgvector'
      - 'DATABASE_URL=postgresql://user:owuipassword780@db:5432/openwebui'
      - 'OLLAMA_BASE_URL=http://ollama:11434'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.open-webui.rule=Host(`ai.lab.sayem.pro`) || Host(`ai.sayem.pro`)"
      - "traefik.http.routers.open-webui.entrypoints=websecure"
      - "traefik.http.routers.open-webui.tls=true"
      - "traefik.http.routers.open-webui.tls.certresolver=cf-letsencrypt"
      - "traefik.http.services.open-webui.loadbalancer.server.port=8080"
    depends_on:
      - db
      - ollama

    deploy:
      resources:
        limits:
          memory: 2G

  mcpo:
    container_name: mcpo
    image: ghcr.io/open-webui/mcpo:main
    command: mcpo --config /app/config/config.json
    # ports:
    # - "8000:8000"
    environment:
      - ENV=dev
    networks:
      - homelab-net
    volumes:
    - ./config.json:/app/config/config.json
    restart: always



networks:
  homelab-net:
    external: true

