# docker/traefik/traefik.yml
# This is the static configuration for Traefik

api:
  insecure: true

providers:
  docker:
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"

serversTransport:
  insecureSkipVerify: true

entryPoints:
  web:
    address: ":80"
  websecure: # Recommended for HTTPS traffic
    address: ":443"
  traefik: # Entrypoint for the Traefik dashboard
    address: ":8080"

certificatesResolvers:
  cf-letsencrypt:
    acme:
      email: ananta.ap65@gmail.com
      storage: "/letsencrypt/acme.json"
      # Configure DNS-01 challenge (essential for wildcards)
      dnsChallenge:
        provider: cloudflare # Replace with your DNS provider (e.g., cloudflare, namecheap, google, digitalocean)
        delayBeforeCheck: "30s" # Usually fine, but increase if you experience DNS propagation issues

log:
  level: DEBUG # DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  # filePath: "/var/log/traefik/traefik.log" # Uncomment to enable file logging, ensure volume mount for this path
# You might want to add access logs here too
# accessLog:
#   filePath: "/var/log/traefik/access.log"
#   format: common
