services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    # privileged: true
    # network_mode: host
    networks:
      - homelab-net
    environment:
      TZ: "Asia/Dhaka"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`hass.lab.sayem.pro`)"
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.routers.homeassistant.tls=true"
      - "traefik.http.routers.homeassistant.tls.certresolver=cf-letsencrypt"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
      - "traefik.http.services.homeassistant.loadbalancer.serversTransport=insecure-tls@file"

