version: "3.8"
services:
  reverse-proxy:
    container_name: "traefik-proxy-entrypoint"
    image: traefik:v3.4
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Port for the Traefik Web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # So that Traefik can listen to the Docker events (read-only)
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/acme.json:/letsencrypt/acme.json:rw
      - ./config/dynamic:/etc/traefik/dynamic:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=lab.sayem.pro"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.lab.sayem.pro"
      - "traefik.http.routers.traefik-secure.tls.domains[1].main=sayem.pro"
      - "traefik.http.routers.traefik-secure.tls.domains[1].sans=*.sayem.pro"
      - "traefik.http.routers.traefik-secure.service=api@internal"

      - "traefik.http.routers.traefik-secure.entrypoints=web"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.lab.sayem.pro`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cf-letsencrypt"

    env_file:
      - ../../.env

    networks:
      - homelab-net # Reference the shared network

